language: r
cache: packages
dist: trusty
warnings_are_errors: false
r_github_packages:
  - r-lib/covr
notifications:
    on_success: never
    on_failure: never
after_success:
  - Rscript -e 'covr::codecov()'

matrix:
  include:
    - os: osx  ## Block testing vignettes. SOURCE: https://github.com/HenrikBengtsson/illuminaio/blob/master/.travis.yml
      r: release
      latex: false
      r_build_args: --no-build-vignettes  ## WORKAROUND: sectsty.sty missing
      r_check_args: --as-cran --ignore-vignettes
      env: NB='w/out vignettes' ## Just a label
      env: LINTR_COMMENT_BOT=false
