language: r
cache: packages
dist: trusty
warnings_are_errors: false
r_github_packages:
  - r-lib/covr
  - jimhester/lintr
notifications:
    on_success: never
    on_failure: never
after_success:
  - Rscript -e 'covr::codecov()'
env:
  LINTR_COMMENT_BOT=false

env:
  global:
  - R_BUILD_ARGS=" --no-build-vignettes --no-manual "  ## https://github.com/ANTsX/ANTsRCore/blob/master/.travis.yml
  - R_BUILD_ARGS=" --as-cran --ignore-vignettes"
